htmlTemplate("template.html",
             button = actionButton("action", "Calculate !", class = "btn-primary"),
             
             slider_nd = sliderInput("nd", "", 25, 50 , 40.8, step = 0.1),
             results_nd = verbatimTextOutput("nd_seats"),
             slider_syriza = sliderInput("syriza", "", 15, 35 , 20.1, step = 0.1),
             results_syriza = verbatimTextOutput("syriza_seats"),
             slider_pasok = sliderInput("pasok", "", 5, 15 , 11.5, step = 0.1),
             results_pasok = verbatimTextOutput("pasok_seats"),
             slider_kke = sliderInput("kke", "", 1, 10, 7.2, step = 0.1),
             results_kke = verbatimTextOutput("kke_seats"),
             slider_ellisi = sliderInput("ellisi", "",  1, 10 , 4.45, step = 0.1),
             results_ellisi = verbatimTextOutput("ellisi_seats"),
             slider_niki = sliderInput("niki", "",  1, 10, 2.9, step = 0.1),
             results_niki = verbatimTextOutput("niki_seats"),
             slider_plefsi = sliderInput("plefsi", "",  1, 10, 2.6, step = 0.1),
             results_plefsi = verbatimTextOutput("plefsi_seats"),
             slider_mera25 = sliderInput("mera25", "",  1, 10 , 2.9, step = 0.1),
             results_mera25 = verbatimTextOutput("mera25_seats"),
             slider_other1 = sliderInput("other1", "",  0, 10, 0.9, step = 0.1),
             results_other1 = verbatimTextOutput("other1_seats"),
             slider_other2 = sliderInput("other2", "",  0, 10, 0.9, step = 0.1),
             results_other2 = verbatimTextOutput("other2_seats"),
             
             toallocate = verbatimTextOutput("toallocate_server"),
             oop = verbatimTextOutput("oop_server"),
)
