htmlTemplate("template.html",
             button = actionButton("action", "Calculate !", class = "btn-primary"),
             
             slider_nd = sliderInput("nd", "", 25, 50 , 39.9, step = 0.1),
             results_nd = verbatimTextOutput("nd_seats"),
             slider_syriza = sliderInput("syriza", "", 20, 45 , 31,5, step = 0.1),
             results_syriza = verbatimTextOutput("syriza_seats"),
             slider_pasok = sliderInput("pasok", "", 5, 15 , 8.1, step = 0.1),
             results_pasok = verbatimTextOutput("pasok_seats"),
             slider_kke = sliderInput("kke", "", 1, 10, 5.3, step = 0.1),
             results_kke = verbatimTextOutput("kke_seats"),
             slider_ellisi = sliderInput("ellisi", "",  1, 10 , 3.7, step = 0.1),
             results_ellisi = verbatimTextOutput("ellisi_seats"),
             slider_mera25 = sliderInput("mera25", "",  1, 10 , 3.4, step = 0.1),
             results_mera25 = verbatimTextOutput("mera25_seats"),
             slider_other1 = sliderInput("other1", "",  1, 10, 1, step = 0.1),
             results_other1 = verbatimTextOutput("other1_seats"),
             slider_other2 = sliderInput("other2", "",  1, 10, 1, step = 0.1),
             results_other2 = verbatimTextOutput("other2_seats"),
             slider_other3 = sliderInput("other3", "",  1, 10, 1, step = 0.1),
             results_other3 = verbatimTextOutput("other3_seats"),
)
