name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "stesiam" --password-stdin
        docker build . --file Dockerfile --tag stesiam/greek-elections-app:latest
    - name: Push image to DockerHub
      run:
        docker push stesiam/ageing-dashboard:latest
